plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'eclipse'
    id 'org.jpos.jposapp' version '0.0.19'
}

group = 'org.jpos.template'
version = '3.0.2-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

repositories {
    mavenCentral()
    maven { url = uri('https://jpos.org/maven') }
    mavenLocal()
}

dependencies {
    implementation 'org.jpos:jpos:3.0.2-SNAPSHOT'
}

jpos {
    distDir.set('src/dist')
}
