plugins {
    id 'org.jpos.jposapp' version '0.0.17' apply false
}

if (file('libraries.gradle').exists()) {
    apply from: 'libraries.gradle'
}

allprojects {
    apply plugin: 'maven-publish'
    apply plugin: 'idea'
    apply plugin: 'eclipse'

    group = 'org.jpos.template'
    version = '3.0.2-SNAPSHOT'
}

subprojects {
    apply plugin: 'java-library'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(26)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    repositories {
        mavenCentral()
        maven { url 'https://jpos.org/maven' }
        mavenLocal()
    }
}
