plugins {
    id 'org.jpos.jposapp'
}

group = 'org.jpos.template.app'

dependencies {
    implementation(libraries.jpos) {
        exclude(module: 'junit')
        exclude(module: 'hamcrest-core')
    }
    testImplementation libraries.junit
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

test {
    useJUnitPlatform()
}

jpos {
    distDir.set('src/dist')
}
